<?PHP
//資料表
$XFUN_TBL = Array(
	'TABLE_XFUN_admin'		 		=> 'xfun_admin',
	'TABLE_XFUN_admin_group'  		=> 'xfun_admin_group',
	'TABLE_XFUN_menu' 		 		=> 'xfun_menu',
	'TABLE_XFUN_menu_group' 	 	=> 'xfun_menu_group',
	'TABLE_XFUN_rent'		 		=> 'xfun_rent_room',
	'TABLE_XFUN_rent_img'	 		=> 'xfun_rent_img',
	'TABLE_XFUN_rent_date'	 		=> 'xfun_rent_date',
	'TABLE_XFUN_news'		 		=> 'xfun_news',
	'TABLE_XFUN_news_kind'	 		=> 'xfun_news_kind',
	'TABLE_XFUN_products_kind'	 	=> 'xfun_products_kind',
	'TABLE_XFUN_products'	 		=> 'xfun_products',
	'TABLE_XFUN_products_img'		=> 'xfun_products_img',
	'TABLE_XFUN_products_qep'		=> 'xfun_products_eqp',
	'TABLE_XFUN_epaper_email'		=> 'xfun_epaper_mail',
	'TABLE_XFUN_epaper'				=> 'xfun_epaper',
	'TABLE_XFUN_file'				=> 'xfun_file',
	'TABLE_XFUN_bill'				=> 'xfun_bill',
	'TABLE_XFUN_forum'				=> 'xfun_forum',
	'TABLE_XFUN_forum_reply'		=> 'xfun_forum_reply',
	'TABLE_XFUN_forumcatalog'		=> 'xfun_forumcatalog',
	'TABLE_XFUN_member'				=> 'xfun_member',
	'TABLE_XFUN_area' 				=> 'xfun_area',
	'TABLE_XFUN_area_kind'			=> 'xfun_area_kind',
	'TABLE_XFUN_vote' 				=> 'xfun_vote',
	'TABLE_XFUN_vote_kind' 			=> 'xfun_vote_kind',
	'TABLE_XFUN_vote_img' 			=> 'xfun_vote_img',
	'TABLE_XFUN_team_group' 		=> 'xfun_team_group',
	'TABLE_XFUN_team_group_kind' 	=> 'xfun_team_group_kind',
	'TABLE_XFUN_xfun_shopping_item' => 'xfun_shopping_item',
	'TABLE_XFUN_xfun_cartage' 		=> 'xfun_cartage',
	'TABLE_XFUN_xfun_order_msg' 	=> 'xfun_order_msg',
	'TABLE_XFUN_xfun_order_help' 	=> 'xfun_order_help',
	'TABLE_XFUN_xfun_order_list' 	=> 'xfun_order_list',
	'TABLE_XFUN_xfun_artwork_img'   => 'xfun_artwork_img',
	'TABLE_XFUN_xfun_artwork_kind'  => 'xfun_artwork_kind',
	'TABLE_XFUN_xfun_artwork' 	    => 'xfun_artwork'
);
?>
